export const STORE_PROGRESS = 'STORE_PROGRESS';
export const CHANGE_SCENE = 'CHANGE_SCENE';
export const CHOOSE_INTERVIEW_OPTION = 'CHOOSE_INTERVIEW_OPTION';
export const CHOOSE_ARTICLE_TOPIC = 'CHOOSE_ARTICLE_TOPIC';
